iFixit/node-markup

package.json
Since multiple restrictions can be placed upon the version of a dependency, there shouldn't be a space in '>= 0.1.13'.
See: http://package-json-validator.com/
=> package.json: Remove spaces in dependency versions.

ImageMarkupBuilder.js, limit_size.js, nudge.js, shape_circle.js, shape_rectangle.js
A bunch of logic has been moved to re-usable mixins.
There was a decent amount of common code.
Changes in functionality:
* New shape.grow() function
* shape.grow() and .incrementSize() both allow bypassing the size
limits while scaling via the mouse doesn't.
=> Nudge: move size limits and nudging to mixins

ImageMarkupBuilder.js, ImageMarkupCall.js, drag_to_create.js, highlighted_stroke.mixin.js, limit_size.js, mixin.js, nudge.js, shape_circle.js, shape_line.js, shape_rectangle.js, two_point_interactivity.js
* New two_point_interactivity.js mixin
* Should be the basis for all line-based shapes: arrows, lines, gap
markers.
* Handles scaling, controls, creation via mouse, sub-pixel alignment,
conversion to markup
* New highlighted_stroke.js mixin so code is re-used across all shapes
* Change white 1px border to be proportional to line thickness across
all shapes
* Previously it was only 1px wide no matter the resolution of the
image.
* Moved incrementSize() to the nudge.js mixin
* Added mixin.js to compose mixins while allowing each to call the
parent function.
=> Shapes: add support for Lines

package.json
We've merged `ifixit-production` into master on Fabric.js here:
https://github.com/iFixit/fabric.js/pull/1
This repo no longer builds correctly from the `ifixit-production` branch. We need to ref master now.
CC @andyg0808 @danielbeardsley
=> Fix Fabric.js git reference

.gitmodules, package.json
GitHub as disabled the `git://` protocol for security reasons. (See: https://github.blog/2021-09-01-improving-git-protocol-security-github/). This updates a few repo references to use `https://` instead.
=> Move to HTTPS for our git cloning URLs.

run-tests.py
Python doesn't hoist. But the idomatic pattern to work around that is defining our `main` function at the top of the file, and using this magic:
```
if __name__ == "__main__":
main()
```
to automatically run the `main` entrypoint function if this file is executed. We can also then use this file as a library as well, `import`ing, but not immediately kicking off the `main` function.
This is a very nice, and very low risk, quality-of-life refactor.
=> Restructure test file

ImageMarkupCall.js, package.json, validator/ValidateJSON.js
Optimist is [deprecated](https://github.com/substack/node-optimist#deprecation-notice), and has some troublesome dependencies. Specifically, `contextify` on later versions of node. It appears that yargs is a nearly drop-in replacement for optimisit.
[Yargs]() is the well worn successor to optimist. It appears to drop in and work.
CC @iFixit/devops
=> Replace Optimist with Yargs

ImageMarkupBuilder.js, ImageMarkupCall.js, src/utils.js
Lets clean up some of the stray helper functions in our main JS entrypoint modules.
The `clone` and `printJSON` helpers appear to be unused. Drop those.
The `cleanJSON` functions were interesting. I believe that the subtle difference between the integer property lists might have actually been a latent bug. Note especially that the server-side `ImageMarkupCall` outer/wrapper module _was_ performing the clean on the `strokeWidth` property. So that is a bug that can only be exposed on the clientside! See: https://github.com/iFixit/node-markup/commit/d77b777832a34476aa9e791fb248dd9c90caac22
With the two implementations unified and reconciled, we can reuse the same function from the new `utils` module. See: https://github.com/iFixit/node-markup/commit/7e3a82e4bef5905aa73a74ea46d98901b24d96ff
=> Cleanup helper functions

ImageMarkupBuilder.js
This finishes up the basic `eslint` bugs in repo! :tada: 
Mostly dropping unused variables, and "unique-ifying" existing in-scope redeclarations.
This commit in particular is a nice little cleanup: https://github.com/iFixit/node-markup/commit/3e8fe7596f754004f4aa8f45b5b2ae2ca82461d1
Ref #44
=> Eslint fixes in `ImageMarkupBuilder`

.github/workflows/lint.yml, ImageMarkupCall.js
While eslint can also do formatting and style checking, we're currently configuring and using eslint as a "static bug guard". Lets enforce formatting with prettier, and run eslint as well.
Closes #44
=> Run Eslint in Lint Action

ImageMarkupBuilder.js, shapes/index.js, shapes/rectangle.js, src/utils.js
Extract our set of shapes into an index.js on the `shapes/` folder. This is nice to keep the shapes/mixins/Fabric-extensions as a single cohesive module, and out of the way of the main markup parsing.
Move the `isNode` global variable (declared in more than one place) into its own utility function. That way there is a single definition, that we are able to update independently of _many_ callsites.
cr_req 2
=> Extract more utility helpers

ImageMarkupCall.js, run-tests.py
We've got `yargs` handy, but we were still doing many fiddly and manual
`usage` calls around argument validation. Lets push most of the config
and help docs into the `yargs` builder, and simplifiy down our `usage`
to `warnAndExit`.
Also, lets extract out most of the argv validation into it's own
function. This helps to simplify down main `processArgs`.
Note that this should not affect behaviour in any way.
Also note that this makes our `--help` output much nicer:
```sh
$ node ImageMarkupCall.js -h
Example Usage:
node ImageMarkupCall.js [help|-h] - Show this information
node ImageMarkupCall.js <command> [options]
Commands:
ImageMarkupCall.js --json '[json_string]'
Process JSON input
ImageMarkupCall.js --markup '[markup_string]' --input infile.jpg --output outfile.jpg  Process Markup string …
```
=> Use `yargs` to improve interface to ImageMarkupCall

src/markup_to_json.test.js
`convertMarkupToJSON` is a 100+ LoC string-and-data-munging function. Before we can aggressive refactor this guy, we should have an acceptance test at the very least.
This isnt the prettiest, but it is fast, and accurate.
=> Add E2E Acceptance test on `convertMarkupToJSON`

ImageMarkupCall.js, src/markup_to_json.js
The `GM('infile').size` call is async. I thought that was surprising. But that made writing a test for the converter prohibitively difficult. We're on Node v6 here, so we cannot use `async`/`await` either. Promises it is. They're boilerplatey for sure, but easy to simplify to async/await once we're on a later version of node.
The big structural changes here are:
- extracting a function for the `GM.size` call: https://github.com/iFixit/node-markup/commit/57d60803ff8c081dd245f2181e9c8aca040b931b
- Drastically simplifying the iteration logic over the split markup string (im pretty happy with how that refactor end up): 
- https://github.com/iFixit/node-markup/commit/fde3d7e667576536b6dd6f0d5e09c32aedb886ff
- https://github.com/iFixit/node-markup/commit/e5749413f01cb3764c12f10b1e1e1eec02104fba …
=> Refactor `convertMarkupToJSON` to Promises

Dockerfile, package.json
Update our Dockerfile and package.json to target Node 16 (on alpine).
This does not work as presented. We will need to stub out the `run-tests` script to prevent CI fails while we iterate.
But this is a step in the right direction! For now, we will tolerate being broken on master, and rally onward with getting the library patched up to work _correctly_ on Node 16.
This PR as written unlocks a few follow improvement PRs.
qa_req 0 (doesnt actually work, just pass CI for now)
CC @andyg0808
=> Upgrade to node 16, Fabric.js v5.2.1

ImageMarkupBuilder.js, ImageMarkupCall.js, run-tests.py
We were reading the sourceFile, and passing it to Fabric as a `blob`. Now, `fromObject` wants an URL. For local files, we can `resolve` a fully qualified `file://` URL to the source file for processing. Without passing a URL to Fabric.js v5.2.1, our tests crash hard and fast. This gets us much further through tests. See: https://github.com/iFixit/node-markup/commit/ee1c72a3c4b39fbad87d2bba88e51c3ddc4162d4
Next, we need to update our call to `createCanvasForNode`. That's gone, and does not work. The new API involves the `Fabric.Canvas` and `Fabric.StaticCanvas` classes. See: https://github.com/iFixit/node-markup/commit/7208098879aa40fa4c43dbe33b4ec9b963320f68
Lastly, with the previous fixes in place, we were seeing failures around `requestAnimationFrame`. Of course, this API is not …
=> Misc fixes for Fabric.js upgrade

src/markup_to_json.test.js, src/new_markup_to_json.js, test/000066.json, test/00CC00.json, test/66CCFF.json, test/9900CC.json, test/993333.json, test/lines.json, test/simple-lines.json
Talking with @sctice-ifixit and @andyg0808 about this, they were convinced that we could parse markup strings more easily with regex. They were right! Andrew took five minutes and wrote a quick and dirty parser implementation that works for us:
https://stackblitz.com/edit/js-5hvs6f?file=index.js
Without too much work, we can turn this into a simpler markup parser implementation, with much reduced mutation. Further, this implementation is potentially faster, though performance is not a major concern.
The first pass with cleanup/comments can be found here for posterity: https://github.com/iFixit/node-markup/pull/64
There were some rebase/conflict/base-branch shenanigans that made maintaining that specific branch difficult.
As a nice improvement, and to robustly test this new parser, we're …
=> Improve markup parsing

ImageMarkupBuilder.js, run-tests.py
A few easy touchups to make working with the repo a little easier:
- Pass through stderr from the `run-tests.py`. The facilitates debugging.
- Drop a few deprecated functions. These are "in the way" otherwise.
- Pull up a named function to the top-level function scope.
- note that RGB translation function has no state, and only relies on the `const` colorValues map.
Ref: https://github.com/iFixit/ifixit/issues/43782
qa_req 0 (passes tests)
CC @iFixit/devops
=> Miscellaneous quality-of-life fixes

ImageMarkupBuilder.js
Fix a Fabric.js interface mismatch on our latest version.
Specifically, it appears master is trying to pass `borderWidth` to Fabric objects for their strokeWidth. This does not draw  objects as expected. We see that 
Here's a montage of the test images from master:
:warning: Notes:
- The rectangle shape has been shifted slightly now. It appears the "corner" of the shape is now at the edge of the stroke, not centered in the corner as prior. This is difficult to describe, but it appears the position of the rectangle has changed to be about a half strokeWidth in the +X and +Y direction.
- The white shadow/border is not being drawn as expected. Perhaps the mixin is not getting called the way we expect.
With these light fixes applied, we're actually drawing the shapes we expect, pretty close …
=> Bugfix: StrokeWidth

mixins/highlighted_stroke.mixin.js, shapes/arrow.js, shapes/gap.js
Peeking into the fabric source, it looks like the `_stroke` method we're overriding in the [`highlighted_stroke`](https://github.com/iFixit/node-markup/blob/master/mixins/highlighted_stroke.mixin.js) mixin has been renamed to `_renderStroke`. Making sure we override the correct method, we start seeing our customized stroke rendering.
Master:
:exclamation: Edit:
This commit: https://github.com/iFixit/node-markup/pull/73/commits/ddc01aff294d259085d3c2cc1fd0ed8975999b36
which is practically the same fix, for the gap and arrow shapes, fixes the "line based shape" extra endings as well.
See: https://github.com/iFixit/node-markup/pull/73#issuecomment-1244669528
Updated montage :framed_picture: :
This branch:
Our version of Fabric (v1.6) calls into the `_stroke` method (if it exists) in …
=> Bugfix: `_renderStroke` fix custom stroke override method

mixins/highlighted_stroke.mixin.js, shapes/line.js, shapes/rectangle.js
The `strokeLineCap` and `strokeLineJoin` properties we are using for our custom stroke implementation do not match the Canvas API properties for the same.
Ref: (Fabric): http://fabricjs.com/docs/fabric.Line.html#strokeLineCap
This seems to match the SVG name for that property:
Ref: (MDN SVGs): https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-linecap
But not the Canvas API for the same:
Ref: (MDN CanvasRC2D): https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineCap
This repairs the nice rounded edges (for lines, and the drop highlight) for our lines, caps, and rectangles.
<table>
<thead>
<tr>
<th>master</th>
<th>branch</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Ref: …
=> Bugfix: Fix strokeline props

ImageMarkupBuilder.js
In this commit, i erroneously dropped the `borderWidth` property. https://github.com/iFixit/node-markup/pull/72/commits/3ad42ee7b8398168e0c6399c87a46289e17f3555
At the time, using this property was changing object positioning in difficult to explain ways. Presumably fixing our render functions in #73 has corrected the positioning bug. Bring back this property, effectively the strokeWidth, brings the line widths on our test images into much better parity with the oracle images.
qa_req 0
Ref: https://github.com/iFixit/ifixit/issues/43782
CC @iFixit/devops
=> Bugfix: put back borderWidth

ImageMarkupBuilder.js, shapes/circle.js, shapes/line.js, shapes/rectangle.js
In trying to get our generated images to match the test oracles, we've found a few assorted fixes and touchups.
An otherwise difficult to account for position bug is fixed in: https://github.com/iFixit/node-markup/commit/3ffa73aa0dfe9e7ef0d305f2e4412e6fdb4c6156
I dont love that we need a mutation based bump like that, but that fix brings the line and rectangle position into near pixel-perfect parity with the test oracle images. At the least, it highlights the bug, until we can better maintain the positioning logic.
Also, on testing using this new latest version we found that the object/canvas caching was breaking, in surprising ways, in-browser. Disabling that caching (temporarily?) gets the UI working reasonably well.
See individual commit messages for more details.
qa_req 0 (tests are …
=> Misc Image writing fixes

ImageMarkupBuilder.js
We're using a custom build of Fabric.js internally. In order to facilitate dependency management, export our Fabric dependency from `Builder`. This lets us avoid manually managing this peer dependency.
We intend upstream to explicitly reuse this Fabric.js dependency:
https://github.com/iFixit/ifixit/blob/394eeb1c6164e88360827aa9bc3e6013f661e44d/carpenter-frontend/Shared/FrameModules/Image/image_markers_next.js#L258
Ref: https://github.com/iFixit/ifixit/issues/43782
CC @iFixit/devops
=> Export Fabric

ImageMarkupBuilder.js, ImageMarkupCall.js
Specifically, we want to import our Builder in the browser context. Currently, this fails hard and fast at our `require` of `path` in the Builder.
In this commit: https://github.com/iFixit/node-markup/commit/ee1c72a3c4b39fbad87d2bba88e51c3ddc4162d4 during the Fabric upgrade, we switched to passing a full `file://` URL in the options to `Fabric.Image.fromObject`. This was to handle a change to the Fabric internals where we now require an URL.
We can use `path.resolve` to build our `file://` URL, but `path` is a Node specific dependency, and breaks at webpack (can't resolve that module without a polyfill.)
We can avoid the trouble by pre-resolving this path/URL in the outer `ImageMarkupCall` wrapper. Since that file is the node-specific entrypoint, it is safe for us to require and use …
=> Avoid node dependencies in Builder
